#############################################################################
# Makefile for building: Qt-Navegador-exe.app/Contents/MacOS/Qt-Navegador-exe
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  Qt-Navegador/Qt-Navegador.pro
# Template: app
# Command: /Applications/Qt/5.2.0/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Qt-Navegador/Qt-Navegador.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_QUICK_LIB -DQT_POSITIONING_LIB -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WEBKIT_LIB -DQT_MULTIMEDIA_LIB -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_SENSORS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/Applications/Qt/5.2.0/clang_64/mkspecs/macx-clang -IQt-Navegador -I/Applications/Qt/5.2.0/clang_64/lib/QtWebKitWidgets.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtQuick.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtPositioning.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtOpenGL.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtWebKit.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtQml.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtSensors.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers -I/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -F/Applications/Qt/5.2.0/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Applications/Qt/5.2.0/clang_64/lib -framework QtWebKitWidgets -framework QtMultimediaWidgets -framework QtMultimedia -framework QtGui -framework QtCore -framework QtNetwork -framework QtWidgets -framework QtQuick -framework QtQml -framework QtPositioning -framework QtOpenGL -framework QtPrintSupport -framework QtWebKit -framework QtSql -framework QtSensors -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Applications/Qt/5.2.0/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Qt-Navegador/main.cpp \
		Qt-Navegador/mainwindow.cpp \
		Qt-Navegador/webbrowser.cpp \
		Qt-Navegador/qbookmarkreader.cpp \
		Qt-Navegador/bookmarkvector.cpp qrc_resources.cpp \
		moc_mainwindow.cpp \
		moc_webbrowser.cpp
OBJECTS       = main.o \
		mainwindow.o \
		webbrowser.o \
		qbookmarkreader.o \
		bookmarkvector.o \
		qrc_resources.o \
		moc_mainwindow.o \
		moc_webbrowser.o
DIST          = /Applications/Qt/5.2.0/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/spec_post.prf \
		Qt-Navegador/.qmake.stash \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/qml_debug.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/declarative_debug.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/lex.prf \
		Qt-Navegador/Qt-Navegador/Qt-Navegador.pro \
		Qt-Navegador/Qt-Navegador/resources.qrc \
		Qt-Navegador/Qt-Navegador.pro
QMAKE_TARGET  = Qt-Navegador-exe
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Qt-Navegador-exe.app/Contents/MacOS/Qt-Navegador-exe

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile Qt-Navegador-exe.app/Contents/PkgInfo Qt-Navegador-exe.app/Contents/Resources/empty.lproj Qt-Navegador-exe.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d Qt-Navegador-exe.app/Contents/MacOS/ || mkdir -p Qt-Navegador-exe.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Qt-Navegador/Qt-Navegador.pro /Applications/Qt/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf /Applications/Qt/5.2.0/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/qml_debug.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/declarative_debug.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt/5.2.0/clang_64/mkspecs/features/lex.prf \
		Qt-Navegador/Qt-Navegador.pro \
		Qt-Navegador/resources.qrc \
		/Applications/Qt/5.2.0/clang_64/lib/QtWebKitWidgets.framework/QtWebKitWidgets.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/QtMultimediaWidgets.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtGui.framework/QtGui.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/QtCore.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtQuick.framework/QtQuick.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtQml.framework/QtQml.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtPositioning.framework/QtPositioning.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtWebKit.framework/QtWebKit.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtSql.framework/QtSql.prl \
		/Applications/Qt/5.2.0/clang_64/lib/QtSensors.framework/QtSensors.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Qt-Navegador/Qt-Navegador.pro
/Applications/Qt/5.2.0/clang_64/mkspecs/features/spec_pre.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/qdevice.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/device_config.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/common/shell-unix.conf:
/Applications/Qt/5.2.0/clang_64/mkspecs/common/unix.conf:
/Applications/Qt/5.2.0/clang_64/mkspecs/common/mac.conf:
/Applications/Qt/5.2.0/clang_64/mkspecs/common/macx.conf:
/Applications/Qt/5.2.0/clang_64/mkspecs/common/gcc-base.conf:
/Applications/Qt/5.2.0/clang_64/mkspecs/common/gcc-base-mac.conf:
/Applications/Qt/5.2.0/clang_64/mkspecs/common/clang.conf:
/Applications/Qt/5.2.0/clang_64/mkspecs/common/clang-mac.conf:
/Applications/Qt/5.2.0/clang_64/mkspecs/qconfig.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/qt_functions.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/qt_config.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/default_pre.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/resolve_config.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/default_post.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/qml_debug.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/declarative_debug.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/warn_on.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/qt.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/resources.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/moc.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/unix/opengl.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/uic.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/unix/thread.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/mac/rez.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/exceptions.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/yacc.prf:
/Applications/Qt/5.2.0/clang_64/mkspecs/features/lex.prf:
Qt-Navegador/Qt-Navegador.pro:
Qt-Navegador/resources.qrc:
/Applications/Qt/5.2.0/clang_64/lib/QtWebKitWidgets.framework/QtWebKitWidgets.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/QtMultimediaWidgets.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtGui.framework/QtGui.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/QtCore.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtQuick.framework/QtQuick.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtQml.framework/QtQml.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtPositioning.framework/QtPositioning.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtWebKit.framework/QtWebKit.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtSql.framework/QtSql.prl:
/Applications/Qt/5.2.0/clang_64/lib/QtSensors.framework/QtSensors.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Qt-Navegador/Qt-Navegador.pro

qmake_all: FORCE

Qt-Navegador-exe.app/Contents/PkgInfo: 
	@test -d Qt-Navegador-exe.app/Contents || mkdir -p Qt-Navegador-exe.app/Contents
	@$(DEL_FILE) Qt-Navegador-exe.app/Contents/PkgInfo
	@echo "APPL????" >Qt-Navegador-exe.app/Contents/PkgInfo
Qt-Navegador-exe.app/Contents/Resources/empty.lproj: 
	@test -d Qt-Navegador-exe.app/Contents/Resources || mkdir -p Qt-Navegador-exe.app/Contents/Resources
	@touch Qt-Navegador-exe.app/Contents/Resources/empty.lproj
	
Qt-Navegador-exe.app/Contents/Info.plist: 
	@test -d Qt-Navegador-exe.app/Contents || mkdir -p Qt-Navegador-exe.app/Contents
	@$(DEL_FILE) Qt-Navegador-exe.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Qt-Navegador-exe,g" -e "s,@TYPEINFO@,????,g" /Applications/Qt/5.2.0/clang_64/mkspecs/macx-clang/Info.plist.app >Qt-Navegador-exe.app/Contents/Info.plist
dist: 
	@test -d .tmp/Qt-Navegador-exe1.0.0 || mkdir -p .tmp/Qt-Navegador-exe1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Qt-Navegador-exe1.0.0/ && $(COPY_FILE) --parents Qt-Navegador/resources.qrc .tmp/Qt-Navegador-exe1.0.0/ && $(COPY_FILE) --parents Qt-Navegador/mainwindow.h Qt-Navegador/webbrowser.h Qt-Navegador/qbookmarkreader.h Qt-Navegador/bookmarkvector.h .tmp/Qt-Navegador-exe1.0.0/ && $(COPY_FILE) --parents Qt-Navegador/main.cpp Qt-Navegador/mainwindow.cpp Qt-Navegador/webbrowser.cpp Qt-Navegador/qbookmarkreader.cpp Qt-Navegador/bookmarkvector.cpp .tmp/Qt-Navegador-exe1.0.0/ && (cd `dirname .tmp/Qt-Navegador-exe1.0.0` && $(TAR) Qt-Navegador-exe1.0.0.tar Qt-Navegador-exe1.0.0 && $(COMPRESS) Qt-Navegador-exe1.0.0.tar) && $(MOVE) `dirname .tmp/Qt-Navegador-exe1.0.0`/Qt-Navegador-exe1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Qt-Navegador-exe1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r Qt-Navegador-exe.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: Qt-Navegador/resources.qrc \
		Qt-Navegador/resources/go-previous.png \
		Qt-Navegador/resources/refresh.png \
		Qt-Navegador/resources/cancel.png \
		Qt-Navegador/resources/go-home.png \
		Qt-Navegador/resources/go-next.png
	/Applications/Qt/5.2.0/clang_64/bin/rcc -name resources Qt-Navegador/resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_webbrowser.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_webbrowser.cpp
moc_mainwindow.cpp: /Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		Qt-Navegador/webbrowser.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGridLayout \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWebKitWidgets.framework/Versions/5/Headers/QWebView \
		/Applications/Qt/5.2.0/clang_64/lib/QtWebKitWidgets.framework/Versions/5/Headers/qwebview.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLineEdit \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QToolButton \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QIODevice \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qiodevice.h \
		Qt-Navegador/qbookmarkreader.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QXmlStreamReader \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qxmlstream.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		Qt-Navegador/mainwindow.h
	/Applications/Qt/5.2.0/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) Qt-Navegador/mainwindow.h -o moc_mainwindow.cpp

moc_webbrowser.cpp: /Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGridLayout \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWebKitWidgets.framework/Versions/5/Headers/QWebView \
		/Applications/Qt/5.2.0/clang_64/lib/QtWebKitWidgets.framework/Versions/5/Headers/qwebview.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLineEdit \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QToolButton \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QIODevice \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qiodevice.h \
		Qt-Navegador/qbookmarkreader.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QXmlStreamReader \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qxmlstream.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		Qt-Navegador/webbrowser.h
	/Applications/Qt/5.2.0/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) Qt-Navegador/webbrowser.h -o moc_webbrowser.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: Qt-Navegador/main.cpp Qt-Navegador/mainwindow.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		Qt-Navegador/webbrowser.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGridLayout \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWebKitWidgets.framework/Versions/5/Headers/QWebView \
		/Applications/Qt/5.2.0/clang_64/lib/QtWebKitWidgets.framework/Versions/5/Headers/qwebview.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLineEdit \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QToolButton \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QIODevice \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qiodevice.h \
		Qt-Navegador/qbookmarkreader.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QXmlStreamReader \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qxmlstream.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o Qt-Navegador/main.cpp

mainwindow.o: Qt-Navegador/mainwindow.cpp Qt-Navegador/mainwindow.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		Qt-Navegador/webbrowser.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGridLayout \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWebKitWidgets.framework/Versions/5/Headers/QWebView \
		/Applications/Qt/5.2.0/clang_64/lib/QtWebKitWidgets.framework/Versions/5/Headers/qwebview.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLineEdit \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QToolButton \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QIODevice \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qiodevice.h \
		Qt-Navegador/qbookmarkreader.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QXmlStreamReader \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qxmlstream.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o Qt-Navegador/mainwindow.cpp

webbrowser.o: Qt-Navegador/webbrowser.cpp Qt-Navegador/webbrowser.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGridLayout \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWebKitWidgets.framework/Versions/5/Headers/QWebView \
		/Applications/Qt/5.2.0/clang_64/lib/QtWebKitWidgets.framework/Versions/5/Headers/qwebview.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLineEdit \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QToolButton \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Applications/Qt/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QIODevice \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qiodevice.h \
		Qt-Navegador/qbookmarkreader.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QXmlStreamReader \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qxmlstream.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o webbrowser.o Qt-Navegador/webbrowser.cpp

qbookmarkreader.o: Qt-Navegador/qbookmarkreader.cpp Qt-Navegador/qbookmarkreader.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QXmlStreamReader \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qxmlstream.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qbookmarkreader.o Qt-Navegador/qbookmarkreader.cpp

bookmarkvector.o: Qt-Navegador/bookmarkvector.cpp Qt-Navegador/bookmarkvector.h \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		/Applications/Qt/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bookmarkvector.o Qt-Navegador/bookmarkvector.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_webbrowser.o: moc_webbrowser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_webbrowser.o moc_webbrowser.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

