#############################################################################
# Makefile for building: Qt-Navegador-exe
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  Qt-Navegador/Qt-Navegador.pro
# Template: app
# Command: /home/manwe/Qt5.2.1/5.2.1/gcc/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Qt-Navegador/Qt-Navegador.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_QUICK_LIB -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WEBKIT_LIB -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_SENSORS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../Qt5.2.1/5.2.1/gcc/mkspecs/linux-g++ -IQt-Navegador -I../../Qt5.2.1/5.2.1/gcc/include -I../../Qt5.2.1/5.2.1/gcc/include/QtWebKitWidgets -I../../Qt5.2.1/5.2.1/gcc/include/QtQuick -I../../Qt5.2.1/5.2.1/gcc/include/QtOpenGL -I../../Qt5.2.1/5.2.1/gcc/include/QtPrintSupport -I../../Qt5.2.1/5.2.1/gcc/include/QtWebKit -I../../Qt5.2.1/5.2.1/gcc/include/QtQml -I../../Qt5.2.1/5.2.1/gcc/include/QtWidgets -I../../Qt5.2.1/5.2.1/gcc/include/QtNetwork -I../../Qt5.2.1/5.2.1/gcc/include/QtPositioning -I../../Qt5.2.1/5.2.1/gcc/include/QtSensors -I../../Qt5.2.1/5.2.1/gcc/include/QtGui -I../../Qt5.2.1/5.2.1/gcc/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/manwe/Qt5.2.1/5.2.1/gcc -Wl,-rpath,/home/manwe/Qt5.2.1/5.2.1/gcc/lib -Wl,-rpath-link,/home/manwe/Qt5.2.1/5.2.1/gcc/lib
LIBS          = $(SUBLIBS) -L/home/manwe/Qt5.2.1/5.2.1/gcc/lib -lQt5WebKitWidgets -lX11 -lxslt -lgio-2.0 -lgstapp-0.10 -lgstinterfaces-0.10 -lgstpbutils-0.10 -pthread -lgstvideo-0.10 -lgstbase-0.10 -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lxml2 -lgthread-2.0 -lrt -lglib-2.0 -lQt5Sql -lQt5Quick -lQt5OpenGL -lQt5PrintSupport -lQt5WebKit -lQt5Qml -lQt5Widgets -lQt5Network -lQt5Positioning -lQt5Sensors -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/manwe/Qt5.2.1/5.2.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Qt-Navegador/main.cpp \
		Qt-Navegador/mainwindow.cpp \
		Qt-Navegador/webbrowser.cpp \
		Qt-Navegador/msginput.cpp qrc_resources.cpp \
		moc_mainwindow.cpp \
		moc_webbrowser.cpp \
		moc_msginput.cpp
OBJECTS       = main.o \
		mainwindow.o \
		webbrowser.o \
		msginput.o \
		qrc_resources.o \
		moc_mainwindow.o \
		moc_webbrowser.o \
		moc_msginput.o
DIST          = ../Qt5.2.1/5.2.1/gcc/mkspecs/features/spec_pre.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/common/shell-unix.conf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/common/unix.conf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/common/linux.conf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/common/gcc-base.conf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/common/g++-base.conf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/common/g++-unix.conf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/qconfig.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_core.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_core_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_designer.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_gui.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_help.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_help_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_network.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_network_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_nfc.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_positioning.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qml.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_quick.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_script.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_script_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sql.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_svg.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xml.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/qt_functions.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/qt_config.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/linux-g++/qmake.conf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/spec_post.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/exclusive_builds.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/default_pre.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/resolve_config.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/default_post.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/qml_debug.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/declarative_debug.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/warn_on.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/qt.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/resources.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/moc.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/unix/opengl.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/uic.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/unix/thread.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/testcase_targets.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/exceptions.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/yacc.prf \
		../Qt5.2.1/5.2.1/gcc/mkspecs/features/lex.prf \
		Qt-Navegador/Qt-Navegador/Qt-Navegador.pro \
		Qt-Navegador/Qt-Navegador/resources.qrc \
		Qt-Navegador/Qt-Navegador.pro
QMAKE_TARGET  = Qt-Navegador-exe
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Qt-Navegador-exe


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: Qt-Navegador/Qt-Navegador.pro ../../Qt5.2.1/5.2.1/gcc/mkspecs/features/spec_pre.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/common/shell-unix.conf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/common/unix.conf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/common/linux.conf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/common/gcc-base.conf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/common/g++-base.conf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/common/g++-unix.conf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/qconfig.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qt_functions.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qt_config.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/linux-g++/qmake.conf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/spec_post.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/default_pre.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/resolve_config.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/default_post.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qml_debug.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/declarative_debug.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/warn_on.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qt.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/resources.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/moc.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/unix/opengl.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/uic.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/unix/thread.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/testcase_targets.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/exceptions.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/yacc.prf \
		../../Qt5.2.1/5.2.1/gcc/mkspecs/features/lex.prf \
		Qt-Navegador/Qt-Navegador.pro \
		Qt-Navegador/resources.qrc \
		/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5WebKitWidgets.prl \
		/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5Quick.prl \
		/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5Qml.prl \
		/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5Network.prl \
		/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5Core.prl \
		/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5Gui.prl \
		/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5OpenGL.prl \
		/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5Widgets.prl \
		/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5PrintSupport.prl \
		/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5WebKit.prl \
		/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5Sql.prl \
		/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5Positioning.prl \
		/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5Sensors.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Qt-Navegador/Qt-Navegador.pro
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/spec_pre.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/common/shell-unix.conf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/common/unix.conf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/common/linux.conf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/common/gcc-base.conf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/common/gcc-base-unix.conf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/common/g++-base.conf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/common/g++-unix.conf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/qconfig.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_core.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_declarative.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_help.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_network.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_script.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkit.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qt_functions.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qt_config.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/linux-g++/qmake.conf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/spec_post.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/exclusive_builds.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/default_pre.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/resolve_config.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/default_post.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qml_debug.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/declarative_debug.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/warn_on.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/qt.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/resources.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/moc.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/unix/opengl.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/uic.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/unix/thread.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/testcase_targets.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/exceptions.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/yacc.prf:
../../Qt5.2.1/5.2.1/gcc/mkspecs/features/lex.prf:
Qt-Navegador/Qt-Navegador.pro:
Qt-Navegador/resources.qrc:
/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5WebKitWidgets.prl:
/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5Quick.prl:
/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5Qml.prl:
/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5Network.prl:
/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5Core.prl:
/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5Gui.prl:
/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5OpenGL.prl:
/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5Widgets.prl:
/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5PrintSupport.prl:
/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5WebKit.prl:
/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5Sql.prl:
/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5Positioning.prl:
/home/manwe/Qt5.2.1/5.2.1/gcc/lib/libQt5Sensors.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Qt-Navegador/Qt-Navegador.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/Qt-Navegador-exe1.0.0 || mkdir -p .tmp/Qt-Navegador-exe1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Qt-Navegador-exe1.0.0/ && $(COPY_FILE) --parents Qt-Navegador/resources.qrc .tmp/Qt-Navegador-exe1.0.0/ && $(COPY_FILE) --parents Qt-Navegador/mainwindow.h Qt-Navegador/webbrowser.h Qt-Navegador/msginput.h .tmp/Qt-Navegador-exe1.0.0/ && $(COPY_FILE) --parents Qt-Navegador/main.cpp Qt-Navegador/mainwindow.cpp Qt-Navegador/webbrowser.cpp Qt-Navegador/msginput.cpp .tmp/Qt-Navegador-exe1.0.0/ && (cd `dirname .tmp/Qt-Navegador-exe1.0.0` && $(TAR) Qt-Navegador-exe1.0.0.tar Qt-Navegador-exe1.0.0 && $(COMPRESS) Qt-Navegador-exe1.0.0.tar) && $(MOVE) `dirname .tmp/Qt-Navegador-exe1.0.0`/Qt-Navegador-exe1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Qt-Navegador-exe1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: Qt-Navegador/resources.qrc \
		Qt-Navegador/resources/addinicio.png \
		Qt-Navegador/resources/go-home.png \
		Qt-Navegador/resources/go-previous.png \
		Qt-Navegador/resources/marcador.png \
		Qt-Navegador/resources/go-next.png \
		Qt-Navegador/resources/refresh.png \
		Qt-Navegador/resources/cancel.png
	/home/manwe/Qt5.2.1/5.2.1/gcc/bin/rcc -name resources Qt-Navegador/resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_webbrowser.cpp moc_msginput.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_webbrowser.cpp moc_msginput.cpp
moc_mainwindow.cpp: ../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMainWindow \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmainwindow.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qwidget.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobal.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qconfig.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfeatures.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobalstatic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_integrity.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_power.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_alpha.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bfin.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_s390.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sparc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmutex.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlogging.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qflags.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsysinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qnamespace.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstring.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qchar.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbytearray.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrefcount.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qarraydata.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlist.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiterator.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetatype.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qisenum.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmargins.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrect.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsize.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpoint.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpaintdevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpalette.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcolor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qrgb.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringlist.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatastream.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiodevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpair.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qregexp.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qbrush.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvector.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qmatrix.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpolygon.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qregion.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qline.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtransform.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainterpath.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qimage.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpixmap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qshareddata.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qhash.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfont.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontmetrics.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcursor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qkeysequence.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qevent.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvariant.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdebug.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtextstream.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlocale.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qset.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurlquery.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfile.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfiledevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qvector2d.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtouchdevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtabwidget.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qicon.h \
		Qt-Navegador/webbrowser.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QGridLayout \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qgridlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayoutitem.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qboxlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKitWidgets/QWebView \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKitWidgets/qwebview.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKit/qwebkitglobal.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKitWidgets/qwebpage.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKit/qwebsettings.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainter.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextoption.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpen.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qnetworkaccessmanager.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/QObject \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/QSslConfiguration \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslconfiguration.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslsocket.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qtcpsocket.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qabstractsocket.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslerror.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslcertificate.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcryptographichash.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatetime.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qssl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/QFlags \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QLineEdit \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlineedit.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qframe.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextcursor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextformat.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QToolButton \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtoolbutton.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractbutton.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QWidget \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/QVector \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QAction \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qaction.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qactiongroup.h \
		Qt-Navegador/msginput.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QDialog \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qdialog.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QLabel \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlabel.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QToolBar \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtoolbar.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/QVariant \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMenuBar \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmenubar.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmenu.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMenu \
		Qt-Navegador/mainwindow.h
	/home/manwe/Qt5.2.1/5.2.1/gcc/bin/moc $(DEFINES) $(INCPATH) Qt-Navegador/mainwindow.h -o moc_mainwindow.cpp

moc_webbrowser.cpp: ../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QGridLayout \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qgridlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qnamespace.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobal.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qconfig.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfeatures.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobalstatic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_integrity.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_power.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_alpha.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bfin.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_s390.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sparc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmutex.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlogging.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qflags.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsysinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstring.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qchar.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbytearray.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrefcount.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qarraydata.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlist.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiterator.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetatype.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qisenum.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayoutitem.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrect.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsize.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpoint.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmargins.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qboxlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qwidget.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpaintdevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpalette.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcolor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qrgb.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringlist.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatastream.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiodevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpair.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qregexp.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qbrush.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvector.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qmatrix.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpolygon.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qregion.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qline.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtransform.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainterpath.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qimage.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpixmap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qshareddata.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qhash.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfont.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontmetrics.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcursor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qkeysequence.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qevent.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvariant.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdebug.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtextstream.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlocale.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qset.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurlquery.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfile.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfiledevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qvector2d.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtouchdevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKitWidgets/QWebView \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKitWidgets/qwebview.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKit/qwebkitglobal.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKitWidgets/qwebpage.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKit/qwebsettings.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qicon.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainter.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextoption.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpen.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qnetworkaccessmanager.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/QObject \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/QSslConfiguration \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslconfiguration.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslsocket.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qtcpsocket.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qabstractsocket.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslerror.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslcertificate.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcryptographichash.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatetime.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qssl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/QFlags \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QLineEdit \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlineedit.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qframe.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextcursor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextformat.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QToolButton \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtoolbutton.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractbutton.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QWidget \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/QVector \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QAction \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qaction.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qactiongroup.h \
		Qt-Navegador/webbrowser.h
	/home/manwe/Qt5.2.1/5.2.1/gcc/bin/moc $(DEFINES) $(INCPATH) Qt-Navegador/webbrowser.h -o moc_webbrowser.cpp

moc_msginput.cpp: ../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QDialog \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qdialog.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qwidget.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobal.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qconfig.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfeatures.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobalstatic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_integrity.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_power.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_alpha.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bfin.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_s390.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sparc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmutex.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlogging.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qflags.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsysinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qnamespace.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstring.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qchar.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbytearray.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrefcount.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qarraydata.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlist.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiterator.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetatype.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qisenum.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmargins.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrect.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsize.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpoint.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpaintdevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpalette.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcolor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qrgb.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringlist.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatastream.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiodevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpair.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qregexp.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qbrush.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvector.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qmatrix.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpolygon.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qregion.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qline.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtransform.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainterpath.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qimage.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpixmap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qshareddata.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qhash.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfont.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontmetrics.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcursor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qkeysequence.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qevent.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvariant.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdebug.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtextstream.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlocale.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qset.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurlquery.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfile.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfiledevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qvector2d.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtouchdevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QLineEdit \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlineedit.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qframe.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextcursor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextformat.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpen.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextoption.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QToolButton \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtoolbutton.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractbutton.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qicon.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QGridLayout \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qgridlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayoutitem.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qboxlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QLabel \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlabel.h \
		Qt-Navegador/msginput.h
	/home/manwe/Qt5.2.1/5.2.1/gcc/bin/moc $(DEFINES) $(INCPATH) Qt-Navegador/msginput.h -o moc_msginput.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: Qt-Navegador/main.cpp Qt-Navegador/mainwindow.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMainWindow \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmainwindow.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qwidget.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobal.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qconfig.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfeatures.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobalstatic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_integrity.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_power.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_alpha.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bfin.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_s390.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sparc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmutex.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlogging.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qflags.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsysinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qnamespace.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstring.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qchar.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbytearray.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrefcount.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qarraydata.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlist.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiterator.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetatype.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qisenum.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmargins.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrect.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsize.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpoint.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpaintdevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpalette.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcolor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qrgb.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringlist.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatastream.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiodevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpair.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qregexp.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qbrush.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvector.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qmatrix.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpolygon.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qregion.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qline.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtransform.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainterpath.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qimage.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpixmap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qshareddata.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qhash.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfont.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontmetrics.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcursor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qkeysequence.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qevent.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvariant.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdebug.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtextstream.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlocale.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qset.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurlquery.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfile.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfiledevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qvector2d.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtouchdevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtabwidget.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qicon.h \
		Qt-Navegador/webbrowser.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QGridLayout \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qgridlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayoutitem.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qboxlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKitWidgets/QWebView \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKitWidgets/qwebview.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKit/qwebkitglobal.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKitWidgets/qwebpage.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKit/qwebsettings.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainter.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextoption.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpen.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qnetworkaccessmanager.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/QObject \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/QSslConfiguration \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslconfiguration.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslsocket.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qtcpsocket.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qabstractsocket.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslerror.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslcertificate.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcryptographichash.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatetime.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qssl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/QFlags \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QLineEdit \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlineedit.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qframe.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextcursor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextformat.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QToolButton \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtoolbutton.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractbutton.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QWidget \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/QVector \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QAction \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qaction.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qactiongroup.h \
		Qt-Navegador/msginput.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QDialog \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qdialog.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QLabel \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlabel.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QToolBar \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtoolbar.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/QVariant \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMenuBar \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmenubar.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmenu.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMenu \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QApplication \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qapplication.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcoreapplication.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qeventloop.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qdesktopwidget.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qguiapplication.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o Qt-Navegador/main.cpp

mainwindow.o: Qt-Navegador/mainwindow.cpp Qt-Navegador/mainwindow.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMainWindow \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmainwindow.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qwidget.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobal.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qconfig.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfeatures.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobalstatic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_integrity.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_power.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_alpha.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bfin.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_s390.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sparc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmutex.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlogging.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qflags.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsysinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qnamespace.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstring.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qchar.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbytearray.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrefcount.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qarraydata.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlist.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiterator.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetatype.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qisenum.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmargins.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrect.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsize.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpoint.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpaintdevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpalette.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcolor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qrgb.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringlist.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatastream.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiodevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpair.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qregexp.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qbrush.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvector.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qmatrix.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpolygon.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qregion.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qline.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtransform.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainterpath.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qimage.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpixmap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qshareddata.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qhash.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfont.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontmetrics.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcursor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qkeysequence.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qevent.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvariant.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdebug.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtextstream.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlocale.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qset.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurlquery.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfile.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfiledevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qvector2d.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtouchdevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtabwidget.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qicon.h \
		Qt-Navegador/webbrowser.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QGridLayout \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qgridlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayoutitem.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qboxlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKitWidgets/QWebView \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKitWidgets/qwebview.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKit/qwebkitglobal.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKitWidgets/qwebpage.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKit/qwebsettings.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainter.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextoption.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpen.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qnetworkaccessmanager.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/QObject \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/QSslConfiguration \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslconfiguration.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslsocket.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qtcpsocket.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qabstractsocket.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslerror.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslcertificate.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcryptographichash.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatetime.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qssl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/QFlags \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QLineEdit \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlineedit.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qframe.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextcursor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextformat.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QToolButton \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtoolbutton.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractbutton.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QWidget \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/QVector \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QAction \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qaction.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qactiongroup.h \
		Qt-Navegador/msginput.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QDialog \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qdialog.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QLabel \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlabel.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QToolBar \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtoolbar.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/QVariant \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMenuBar \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmenubar.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qmenu.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QMenu
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o Qt-Navegador/mainwindow.cpp

webbrowser.o: Qt-Navegador/webbrowser.cpp Qt-Navegador/webbrowser.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QGridLayout \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qgridlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qnamespace.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobal.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qconfig.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfeatures.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobalstatic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_integrity.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_power.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_alpha.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bfin.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_s390.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sparc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmutex.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlogging.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qflags.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsysinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstring.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qchar.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbytearray.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrefcount.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qarraydata.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlist.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiterator.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetatype.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qisenum.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayoutitem.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrect.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsize.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpoint.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmargins.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qboxlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qwidget.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpaintdevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpalette.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcolor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qrgb.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringlist.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatastream.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiodevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpair.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qregexp.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qbrush.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvector.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qmatrix.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpolygon.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qregion.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qline.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtransform.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainterpath.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qimage.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpixmap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qshareddata.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qhash.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfont.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontmetrics.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcursor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qkeysequence.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qevent.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvariant.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdebug.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtextstream.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlocale.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qset.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurlquery.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfile.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfiledevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qvector2d.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtouchdevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKitWidgets/QWebView \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKitWidgets/qwebview.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKit/qwebkitglobal.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKitWidgets/qwebpage.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWebKit/qwebsettings.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qicon.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainter.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextoption.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpen.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qnetworkaccessmanager.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/QObject \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/QSslConfiguration \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslconfiguration.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslsocket.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qtcpsocket.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qabstractsocket.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslerror.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qsslcertificate.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcryptographichash.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatetime.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtNetwork/qssl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/QFlags \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QLineEdit \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlineedit.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qframe.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextcursor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextformat.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QToolButton \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtoolbutton.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractbutton.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QWidget \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/QVector \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QAction \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qaction.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qactiongroup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o webbrowser.o Qt-Navegador/webbrowser.cpp

msginput.o: Qt-Navegador/msginput.cpp Qt-Navegador/msginput.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QDialog \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qdialog.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qwidget.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobal.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qconfig.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfeatures.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsystemdetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qprocessordetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcompilerdetection.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qglobalstatic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbasicatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qgenericatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_msvc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_integrity.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qoldbasicatomic.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_vxworks.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_power.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_alpha.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv7.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv6.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_armv5.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_bfin.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_ia64.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_mips.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_s390.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sh4a.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_sparc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_x86.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_cxx11.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_gcc.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qatomic_unix.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmutex.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlogging.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qflags.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypeinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtypetraits.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsysinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qnamespace.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qwindowdefs_win.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstring.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qchar.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qbytearray.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrefcount.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qarraydata.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringbuilder.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlist.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qalgorithms.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiterator.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcoreevent.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qscopedpointer.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmetatype.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvarlengtharray.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontainerfwd.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qisenum.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qobject_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmargins.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qrect.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsize.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpoint.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpaintdevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpalette.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcolor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qrgb.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringlist.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdatastream.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qiodevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qpair.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qregexp.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qstringmatcher.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qbrush.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvector.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qmatrix.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpolygon.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qregion.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qline.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtransform.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpainterpath.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qimage.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpixmap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qshareddata.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qhash.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfont.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontmetrics.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qfontinfo.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qsizepolicy.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qcursor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qkeysequence.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qevent.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qvariant.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qmap.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qdebug.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qtextstream.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qlocale.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qset.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qcontiguouscache.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurl.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qurlquery.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfile.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtCore/qfiledevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qvector2d.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtouchdevice.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QLineEdit \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlineedit.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qframe.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextcursor.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextformat.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qpen.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qtextoption.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QToolButton \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qtoolbutton.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qabstractbutton.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtGui/qicon.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QGridLayout \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qgridlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlayoutitem.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qboxlayout.h \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/QLabel \
		../../Qt5.2.1/5.2.1/gcc/include/QtWidgets/qlabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o msginput.o Qt-Navegador/msginput.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_webbrowser.o: moc_webbrowser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_webbrowser.o moc_webbrowser.cpp

moc_msginput.o: moc_msginput.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_msginput.o moc_msginput.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

